worker_processes auto;
events {
    worker_connections 1024;
}

http {
    upstream project_backends {
    server 10.7.17.157:3001;
    server 10.7.17.37:3002;
}

    server {
        listen 80;
        server_name app.routex.test api.routex.test;
        location / {
            proxy_pass http://project_backends;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
}
